# Generated by Django 5.0.4 on 2024-08-11 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_product_publisher_alter_product_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='publisher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='products', to='api.publisher'),
        ),
        migrations.AlterField(
            model_name='product',
            name='writer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='products', to='api.writer'),
        ),
    ]
