# Generated by Django 5.0.4 on 2024-09-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_image_logoimage_menuitem_socialicon_themecolor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carousel_images/')),
                ('caption', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('icon', models.ImageField(upload_to='social_icons/')),
            ],
        ),
        migrations.RemoveField(
            model_name='ucimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='logoimage',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='socialicon',
            name='icon',
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
        migrations.DeleteModel(
            name='ThemeColor',
        ),
        migrations.DeleteModel(
            name='UcImage',
        ),
        migrations.DeleteModel(
            name='LogoImage',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='SocialIcon',
        ),
    ]
