# Generated by Django 5.0.4 on 2024-09-04 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_logo_submenu_subsubmenu_menu_submenu_sub_sub_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='subsubmenu',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
