# Generated by Django 5.0.4 on 2024-09-04 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_menu_title_alter_submenu_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='sub_menu',
        ),
        migrations.RemoveField(
            model_name='submenu',
            name='sub_sub_menu',
        ),
        migrations.AddField(
            model_name='submenu',
            name='menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='sub_menus', to='api.menu'),
        ),
        migrations.AddField(
            model_name='subsubmenu',
            name='sub_menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Sub_Sub_Menus', to='api.submenu'),
        ),
    ]
