# Generated by Django 5.0.4 on 2024-09-04 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_submenu_menu_remove_subsubmenu_sub_menu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='sub_menus',
        ),
        migrations.RemoveField(
            model_name='submenu',
            name='sub_sub_menus',
        ),
        migrations.AddField(
            model_name='submenu',
            name='menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='sub_menus', to='api.menu'),
        ),
        migrations.AddField(
            model_name='subsubmenu',
            name='sub_menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Sub_Sub_Menus', to='api.submenu'),
        ),
    ]
